<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'UpdateHelper\\' => array($vendorDir . '/kylekatarnls/update-helper/src'),
    'Sabberworm\\CSS' => array($vendorDir . '/sabberworm/php-css-parser/lib'),
    'React\\ZMQ' => array($vendorDir . '/react/zmq/src'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Milon\\Barcode' => array($vendorDir . '/milon/barcode/src'),
    'Lavary\\Menu\\' => array($vendorDir . '/lavary/laravel-menu/src'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
    'Detection' => array($vendorDir . '/mobiledetect/mobiledetectlib/namespaced'),
    'Chencha\\Share' => array($vendorDir . '/chencha/share/src'),
);
